#!/bin/sh
set -e

php_deps="libbrotli1 libevent-2.1-7 libpsl5 libssl3 libzip4 zlib1g libargon2-1 libonig5 libreadline8 libsodium23 libxml2 libicu72 libc-client2007e libkrb5-3 libpcre2-32-0 libpq5 libmemcached11 librabbitmq4 libyaml-0-2"

php_dev_deps="libbrotli-dev libevent-dev libpsl-dev libssl-dev libzip-dev zlib1g-dev libargon2-dev libonig-dev libreadline-dev libsodium-dev libxml2-dev libicu-dev libc-client2007e-dev libkrb5-dev libpcre2-dev libpq-dev libmemcached-dev librabbitmq-dev libyaml-dev"
phpize_deps="autoconf dpkg-dev file g++ gcc libc-dev make pkg-config re2c"
builder_deps="ca-certificates wget xz-utils gnupg"

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Install php dependencies."
	echo
	echo "Commands:"
	echo "    runtime  install dependencies required to php runtime."
	echo "    build    install dependencies required to build stage."
	echo
}

case "$1" in
	build)
	  apt-get update
		apt-get install -y --no-install-recommends $php_dev_deps $phpize_deps $builder_deps
		rm -rf /var/lib/apt/lists/*
		;;

	runtime)
	  apt-get update
		apt-get install -y --no-install-recommends $php_deps
		rm -rf /var/lib/apt/lists/*
		;;

	*)
		usage
	  exit 1
		;;
esac
